### ISSUE TITLE
question: what is used to generate the layout image?

### ISSUE THREAD

**Issue by mattmarcello** [urob/zmk-config#6]
might be cool to add to produce this as a build artifact by default?

**Comment by urob** [comment]
I am currently creating the layout manually. If you want to modify it, you can use mine as starting point: http://www.keyboard-layout-editor.com/#/gists/06469e3337fa76f1c6e95229f5c58522

At some point, I am going to move over to use https://github.com/caksoylar/keymap-drawer to automate things, but I haven't found the time yet to set things up to be fully automated.

**Comment by autoferrit** [comment]
has there been any effort on using keymap drawer? the nodefree repo that this uses seems to be incompatible as there is no root node in the keymap file.

**Comment by urob** [comment]
> has there been any effort on using keymap drawer? the nodefree repo that this uses seems to be incompatible as there is no root node in the keymap file. 

Keymap drawer should work (it does for me). It is smart enough to include all necessary files and expand all macros. 

Two potential stumbling points:
1. Make sure to run it on the root file (eg corneish_zen.keymap). Running it in base.keymap doesn't work since base is intended to be included in another keymap file. 

2. If you include the nodefree-repo as submodule, the online version of keymap drawer will currently fail (there's already a PR that fixes this). In either case, running keymap drawer locally works
